import argparse
import os
import shutil
import time
from dotenv import load_dotenv
from src.graph import create_ase_graph
from src.tools.github_tools import GitHubTool

load_dotenv()

def main():
    parser = argparse.ArgumentParser(description="Simplified Stateful AI Agent")
    parser.add_argument("issue_url", help="GitHub Issue URL to solve")
    args = parser.parse_args()
    
    if not os.getenv("GITHUB_TOKEN") or not os.getenv("GROQ_API_KEY"):
        print("Please ensure GITHUB_TOKEN and GROQ_API_KEY are set.")
        return

    print(f"Starting orchestration for: {args.issue_url}")
    
    gh_tool = GitHubTool()
    issue_details = gh_tool.fetch_issue_details(args.issue_url)
    print(f"Issue Title: {issue_details['title']}")
    
    import time
    import shutil
    import stat
    def remove_readonly(func, path, excinfo):
        os.chmod(path, stat.S_IWRITE)
        func(path)
        
    workspace_dir = os.path.abspath("./workspace_clones/target_repo")
    if os.path.exists(workspace_dir):
        shutil.rmtree(workspace_dir, onerror=remove_readonly)
    os.makedirs(workspace_dir, exist_ok=True)
    print("Cloning repository...")
    success = gh_tool.clone_repository(args.issue_url, workspace_dir)
    if not success:
        print("Failed to clone!")
        return

    # Initialize LangGraph State
    initial_state = {
        "issue_url": args.issue_url,
        "issue_description": f"{issue_details['title']}\\n\\n{issue_details['body']}",
        "repo_path": workspace_dir,
        "files_to_modify": [],
        "current_code": {},
        "updated_code": {},
        "error_history": [],
        "test_passed": False,
        "pr_url": ""
    }

    graph = create_ase_graph()
    
    print("Entering Agent Graph...")
    final_state = None
    try:
        for output in graph.stream(initial_state):
            for agent, state_update in output.items():
                print(f"\n=====================================")
                print(f"+++ Finished Node: {agent.upper()} +++")
                
                if agent == "researcher":
                    print(f"Files selected to modify: {state_update.get('files_to_modify', [])}")
                
                elif agent == "coder":
                    print("Updated Code generated by Coder:")
                    updated = state_update.get("updated_code", {})
                    for filepath, content in updated.items():
                        print(f"\n--- {filepath} ---")
                        print(content)
                        
                elif agent == "tester":
                    passed = state_update.get("test_passed", False)
                    print(f"Test Passed: {passed}")
                    if not passed and state_update.get("error_history"):
                        print(f"Latest Error Logs:\n{state_update['error_history'][-1]}")
                        
                print(f"=====================================\n")
                
            final_state = state_update
            
    except Exception as e:
        print(f"Error executing graph: {e}")
        return

    if final_state and final_state.get("pr_url") and final_state["pr_url"].startswith("http"):
        print(f"Success! Pull Request opened at: {final_state['pr_url']}")
    else:
        print(f"Orchestration completed, but no PR was opened. Status: {final_state.get('pr_url', 'N/A')}")

if __name__ == "__main__":
    main()
